### ISSUE TITLE
Everything everywhere all the time

### ISSUE THREAD

**Issue by vincentvis** [vincentvis/viroli_webserv#25]
- [x] **1.** - @livlaming @ronaldheuts  - Check new branch, if everything is in there and is correct (if not fix it)
- [x] **2.** - check if issue with 94 get requests still exists (@livlaming)
    ~- [ ] 2.1 - if this issue is there... find out why what and fix?~
- [x] **3.** - code review by @vincentvis 
- [x] **4.** - merge branch in main
- [x] **5.** - fork new branches from updated main
  - [x] @ronaldheuts 
  - [x] @livlaming 
  - [x] @vincentvis 
- [ ]  Check if HTTP request headers are case insensitive
- [x] Initialize the server with the given config directives (@ronaldheuts @vincentvis )
- [ ] Check if file descriptors need to be opened in non-blocking mode
- [ ] 411 Length Required - send this response when no Content-Length AND no transfer-encoding Chunked
- [ ] server hangs/crashes when you request an existing directory but without the slash at the end (ex: localhost:8080/uploads)

---

### vincent
- [x] directory listing, autoindex (@vincentvis) 
   - [x] write code
   - [x] make PR
   - [x] get review
   - [x] merge code
- [x] Make at least 1 location block required in each server block (@vincentvis) #27
- [x] Make config file that includes all options that can exist in config files (@vincentvis) #27
- [x] findLocation bug (@livlaming / @vincentvis)
- [x] Error pages (@vincentvis)
  - [x] make html files for error pages 
  - [x] remove error_page directive option for "location" scope
  - [x] create a getter for error pages where it reverts to de default if none is provided
  - [x] remove html file maker and html files
  - [x] add ErrorPage stuff to Response class with something that creates it from scratch
- [x] ~make route accept uploading files (@vincentvis)~ ([see comment](https://github.com/vincentvis/viroli_webserv/issues/25#issuecomment-1263549292))
- [x] choose a cgi
  - [x] implement a cgi
  - [x] GET
  - [x] POST
  - [ ] ~DELETE~
- [ ] Check configparser "is valid uri" thingy
- [ ] on config stage, try to get custom error pages into std::string's once, so we don't have to get the files through poll each time, maybe not even through poll, since we can argue that this is part of the "config" stage
- [ ] hardcode max value for client body at 2mb

---

### ronald
- [x] FileFD - reading files (@ronaldheuts)
- [x] FileFD - writing files (@ronaldheuts)
- [x] implement client_body_size for post request (only for chunked, content-length can be intercepted in header parsing) (@ronaldheuts)
- [x] chunked transfer encoding (@ronaldheuts)
- [x] #77
- [x] Flushing _pollables_ that are marked for removal (INVALID_FD)
- [x] POLLHUP
- [x] Timeout
- [x] have another look at the switch case for __state_
- [x] When error occurs (chunked exceeds max body size, etc.) send response with error page/status
- [x] Remove client when error occurs on read, write, receive and send. (as per correction sheet)(*)
- [x] #78
- [x] Is there a body present after the header has been received when a 'Expect: 100-continue' is present.
- [x] Rename getHeader()/getBody()
- [x] Complete the singleton pattern of PollableFactory
- [x] Quick fix, should be resolved;If you comment out the quick fix in ready() you'll see that a GET request with curl; doesn't come out of the _state END. Besides an infinite pollin loop it creates new httprequests that get stuck because there is no request information since it doesnt get actual new request.
- [x] when it takes a long time to receive (small buffersize) the body (and perhaps due to writing it to a file) a final response (in case of 100-continue at least) will not be send.
- [ ] Check if the pollable destructors clean everything (_requestInterface and such)
- [x] Check for max Header size (?!). Either stop receiving if ending sequence for header is found or max size limit is reached. (error response 431)
- [x] make malloc checks

\* Will the connection be closed without sending a response to the client?
---

### lisa
- [x] findLocation bug (@livlaming)
- [x] getter for keep alive close (@livlaming)
- [x] split targetrequest (@livlaming)
- [x] try/catch block for header parsing(@livlaming)
- [x] create error response after throwing error (@livlaming)
- [x] CGI recognition should  be extended (@livlaming)
- [x] discuss query and fragments with @vincentvis 
- [x] review code (validator, etc)
- [x] create insensitive header parser function
- [x] pull request last version for merging
- [x] RESPONSE
- [x] ERROR RESPONSE
- [x] HTTP Methods
   - [x] GET
   - [x] POST
   - [x] DELETE
- [x] rename Request -> RequestParser
- [x] put all parse errors in RequestParser
- [x] map for content type
- [x] time and date
- [x] catch fix in ClientFD
- [x] check header between post correspondence 100-continue
- [x] make everything lowercase

---

All:
- [x] getter for client_body_size (@livlaming) or (@vincentvis)?
- [x] CGI recognition should checked by (@vincentvis) :)
